//error
export const CLEAR_ERROR = 'CLEAR_ERROR'

//products constant

export const ALL_PRODUCT_REQUEST = 'ALL_PRODUCT_REQUEST'
export const ALL_PRODUCT_SUCCESS = 'ALL_PRODUCT_SUCCESS'
export const ALL_PRODUCT_FAILED = 'ALL_PRODUCT_FAILED'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAILED = 'PRODUCT_DETAILS_FAILED'

//new product
export const NEW_PRODUCT_REQUEST = 'NEW_PRODUCT_REQUEST'
export const NEW_PRODUCT_SUCCESS = 'NEW_PRODUCT_SUCCESS'
export const NEW_PRODUCT_FAILED = 'NEW_PRODUCT_FAIl'
export const NEW_PRODUCT_RESET = 'NEW_PRODUCT_RESET'

//delete
export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIl'
export const DELETE_PRODUCT_RESET = 'DELETE_PRODUCT_RESET'

//update
export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIl'
export const UPDATE_PRODUCT_RESET = 'UPDATE_PRODUCT_RESET'

//MY PRODUCTS
export const MY_PRODUCTS_REQUEST = 'MY_PRODUCT_REQUEST'
export const MY_PRODUCTS_SUCCESS = 'MY_PRODUCT_SUCCESS'
export const MY_PRODUCTS_FAIL = 'MY_PRODUCT_FAIl'

//admin product
export const ADMIN_PRODUCT_REQUEST = 'ADMIN_PRODUCT_REQUEST'
export const ADMIN_PRODUCT_SUCCESS = 'ADMIN_PRODUCT_SUCCESS'
export const ADMIN_PRODUCT_FAIL = 'ADMIN_PRODUCT_FAIl'
export const ADMIN_PRODUCT_RESET = 'ADMIN_PRODUCT_RESET'

//user

//user constant
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_RESET = 'UPDATE_PASSWORD_RESET'
export const UPDATE_PASSWORD_FAILED = 'UPDATE_PASSWORD_FAILED'
//LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_FAILED = 'LOGIN_FAILED'

//load user
export const LOAD_SUCCESS = 'LOAD_SUCCESS'
export const LOAD_REQUEST = 'LOAD_REQUEST'
export const LOAD_FAILED = 'LOAD_FAILED'

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'

//REGISTER
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'

export const ALL_USERS_REQUEST = 'ALL_USER_REQUEST'
export const ALL_USERS_SUCCESS = 'ALL_USER_SUCCESS'
export const ALL_USERS_FAIL = 'ALL_USER_FAIL'

//logout
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'

//cart
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'
export const DELETE_USER_RESET = 'DELETE_USER_RESET'

//shiPping

export const SAVE_SHIPPING_INFO = 'SAVE_SHIPPING_INFO'

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'

export const MY_ORDERS_REQUEST = 'MY_ORDERS_REQUEST'
export const MY_ORDERS_SUCCESS = 'MY_ORDERS_SUCCESS'
export const MY_ORDERS_FAIL = 'MY_ORDERS_FAIL'

export const ALL_ORDERS_REQUEST = 'ALL_ORDERS_REQUEST'
export const ALL_ORDERS_SUCCESS = 'ALL_ORDERS_SUCCESS'
export const ALL_ORDERS_FAIL = 'ALL_ORDERS_FAIL'

export const UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST'
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS'
export const UPDATE_ORDER_RESET = 'UPDATE_ORDER_RESET'
export const UPDATE_ORDER_FAIL = 'UPDATE_ORDER_FAIL'

export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST'
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS'
export const DELETE_ORDER_RESET = 'DELETE_ORDER_RESET'
export const DELETE_ORDER_FAIL = 'DELETE_ORDER_FAIL'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const REQUEST_DETAILS_REQUEST = 'REQUEST_DETAILS_REQUEST'
export const REQUEST_DETAILS_SUCCESS = 'REQUEST_DETAILS_SUCCESS'
export const REQUEST_DETAILS_FAIL = 'REQUEST_DETAILS_FAIL'

export const NEW_REQUEST_REQUEST = 'NEW_REQUEST_REQUEST'
export const NEW_REQUEST_SUCCESS = 'NEW_REQUEST_SUCCESS'
export const NEW_REQUEST_FAIL = 'NEW_REQUEST_FAIL'

export const MY_REQUEST_REQUEST = 'MY_REQUEST_REQUEST'
export const MY_REQUEST_SUCCESS = 'MY_REQUEST_SUCCESS'
export const MY_REQUEST_FAIL = 'MY_REQUEST_FAIL'

export const ALL_REQUEST_REQUEST = 'ALL_REQUEST_REQUEST'
export const ALL_REQUEST_SUCCESS = 'ALL_REQUEST_SUCCESS'
export const ALL_REQUEST_FAIL = 'ALL_REQUEST_FAIL'

export const DELETE_REQUEST_REQUEST = 'DELETE_REQUEST_REQUEST'
export const DELETE_REQUEST_SUCCESS = 'DELETE_REQUEST_SUCCESS'
export const DELETE_REQUEST_FAIL = 'DELETE_REQUEST_FAIL'
export const DELETE_REQUEST_RESET = 'DELETE_REQUEST_RESET'
